"""Add heating table

Revision ID: 4842138b56c6
Revises: 9767077fab13
Create Date: 2025-01-12 16:36:21.570029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4842138b56c6'
down_revision = '9767077fab13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('burn_date', sa.Date(), nullable=False),
    sa.Column('temperature_in', sa.Float(), nullable=False),
    sa.Column('temperature_out', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heating')
    # ### end Alembic commands ###
